@startuml Test

file "Szenarien.json" as szen #LightBlue
file "erzeugerarten.json" as erzeugerarten #LightBlue
file "speicherarten.json" as speicherarten #LightBlue
file "Netto_Installierte_GW.csv" as installed #LightBlue
file "erzeugung_2021.csv" as erzeugung #LightBlue
file "verbrauch_2024.csv" as verbrauch #LightBlue

component "Prognose Erzeugung" as prognose_erzeugung
component "Prognose Verbrauch" as prognose_verbrauch
component "Prognose Speicher" as prognose_speicher

component "Szenario Auswahl" as szenario_auswahl
component "Kosten" as kosten
component "Analyse EE Anteil" as analyse
file "Ausgaben" as ausgaben
component "main" as main

main -[#Black,thickness=3]-> szenario_auswahl : <color:Black>startet</color>

kosten -[#Purple,thickness=2]-> prognose_erzeugung : <color:Purple>ausbauraten</color>
kosten -[#Purple,thickness=2]-> prognose_speicher : <color:Purple>ausbauraten</color>
kosten -[#Purple]-> erzeugerarten : <color:Purple>kosteninformationen</color>
kosten -[#Purple]-> speicherarten : <color:Purple>kosteninformationen</color>

szenario_auswahl -[#Orange,thickness=2]-> szen : <color:Orange>lädt</color>
szenario_auswahl -[#Green,thickness=2]-> prognose_erzeugung : <color:Green>konfiguriert und startet</color>
szenario_auswahl -[#Green,thickness=2]-> prognose_verbrauch : <color:Green>konfiguriert und startet</color>
szenario_auswahl -[#Green,thickness=2]-> prognose_speicher : <color:Green>konfiguriert und startet</color>
szenario_auswahl -[#Green,thickness=2]-> kosten : <color:Green>konfiguriert und startet</color>
szenario_auswahl -[#Green,thickness=2]-> analyse : <color:Green>konfiguriert und startet</color>
szenario_auswahl -[#Orange]-> ausgaben : <color:Orange>erzeugt</color>

note bottom of ausgaben
  <size:30> <&signal>
end note

analyse .[#Red,thickness=2].> prognose_erzeugung : <color:Red>nutzt Ergebnisse</color>
analyse .[#Red,thickness=2].> prognose_verbrauch : <color:Red>nutzt Ergebnisse</color>
analyse .[#Red,thickness=2].> prognose_speicher : <color:Red>nutzt Ergebnisse</color>

prognose_erzeugung -[#Blue]-> installed : <color:Blue>nutzt</color>
prognose_erzeugung -[#Blue]-> erzeugung : <color:Blue>nutzt</color>
prognose_erzeugung -[#Blue]-> erzeugerarten : <color:Blue>nutzt</color>

prognose_verbrauch -[#Blue]-> verbrauch : <color:Blue>nutzt</color>
prognose_speicher -[#Blue]-> speicherarten : <color:Blue>nutzt</color>

@enduml