@startuml Klassendiagramm_Pottkieker

!pragma layout smetana
skinparam ranksep 60
skinparam nodesep 40

database "Datenbank" as db #LightGray
file "Szenarien.json" as szen #LightBlue
file "erzeugerarten.json" as erzeugerarten #LightBlue
file "speicherarten.json" as speicherarten #LightBlue
file "Netto_Installierte_GW.csv" as installed #LightBlue
file "erzeugung_2021.csv" as erzeugung #LightBlue
file "verbrauch_2024.csv" as verbrauch #LightBlue

component "Prognose Erzeugung" as prognose_erzeugung
component "Prognose Verbrauch" as prognose_verbrauch
component "Prognose Speicher" as prognose_speicher 
component "Szenario" as szenario

component "Szenario Auswahl" as szenario_auswahl
component "Kosten" as kosten
component "Analyse EE Anteil" as analyse
file "Ausgaben" as ausgaben
component "main" as main

main -[#Green,thickness=3]-> szenario_auswahl : <color:Green>startet</color>

szenario_auswahl -[#Red,thickness=2]-> szenario : <color:Green>wählt 1 Szenario</color>
szenario_auswahl -[#Red,thickness=2]-> szenario : <color:Green>Durchläuft alle Szenarien</color>

kosten -[#Orange,thickness=2]-> prognose_erzeugung : <color:Orange>ausbauraten</color>
kosten -[#Orange,thickness=2]-> prognose_speicher : <color:Orange>ausbauraten</color>
kosten -[#Orange]-> db : <color:Orange>kosteninformationen</color>

szenario_auswahl -[#Red,thickness=2]-> db : <color:Green>lädt Szenarien</color>
szenario -[#Green,thickness=2]-> prognose_erzeugung : <color:Green>konfiguriert und startet</color>
szenario -[#Green,thickness=2]-> prognose_verbrauch : <color:Green>konfiguriert und startet</color>
szenario -[#Green,thickness=2]-> prognose_speicher : <color:Green>konfiguriert und startet</color>
szenario -[#Green,thickness=2]-> kosten : <color:Green>konfiguriert und startet</color>
szenario -[#Green,thickness=2]-> analyse : <color:Green>konfiguriert und startet</color>
szenario -[#Green]-> ausgaben : <color:Green>erzeugt</color>
note bottom of ausgaben
  <size:30> <&signal>
end note

note right of ausgaben
  **Ergebnisse:**
  | Gesamtkosten | 1.5 Mrd. €   |
  | EE-Anteil    | 65%          |
  | Konventionelle |50 TWh |
end note

analyse -[#Blue,thickness=2]-> prognose_erzeugung : <color:Blue>nutzt Ergebnisse</color>
analyse -[#Blue,thickness=2]-> prognose_verbrauch : <color:Blue>nutzt Ergebnisse</color>
analyse -[#Blue,thickness=2]-> prognose_speicher : <color:Blue>nutzt Ergebnisse</color>

prognose_erzeugung -[#Purple]-> db : <color:Purple>nutzt</color>

prognose_verbrauch -[#Purple]-> db : <color:Purple>nutzt</color>
prognose_speicher -[#Purple]-> db : <color:Purple>nutzt</color>

db -[#Purple,dashed]-> szen 
db -[#Purple,dashed]-> erzeugerarten 
db -[#Purple,dashed]-> speicherarten  
db -[#Purple,dashed]-> installed    
db -[#Purple,dashed]-> erzeugung  
db -[#Purple,dashed]-> verbrauch 

@enduml