@startuml Dunkelflaute

<style>
activity {
    HorizontalAlignment center
}
</style>

start

:Übergabewerte: 
Dataframe der normativen Speichersimulation
Zieljahr in dem Dunkelflaute simuliert werden soll;

:Jahreswerte einfügen;

:Dunkelflauten-Daten aus CSV einlesen;

note right
Tabelle mit Tagen:
-Monat
-Tag
-Anteil realisierte Erneuerbare Energien (Faktor)
end note


:Normativen Speicherverlauf aus Speicher-Prognose kopieren;


:Erzeugungswerte an Dunkelflauten-Tagen neu berechnen anhand Faktoren aus CSV\n MWh = GW ⋅ 1000 ⋅ 1/4 ⋅ Faktor;

:Werte überscheiben;

partition "Schleife über Dunkelflaute Zeitpunkte + 1 Tag vorher und nachher(15 min Auflösung)" {
    
    :Schleife wie bei normativer Speichersimulation 
    nur über begrenzten Bereich;
    

    
}

:Dataframe auf relevante Tage reduzieren ;

:Return Dataframe;

stop
@enduml