@startuml Fallunterscheidung Entladung

<style>
activity {
    HorizontalAlignment center
}

</style>
!pragma useVerticalIf on
start
    
if (Fehlmenge <= 0 oder verfügbare Energie <= 0 ?) then (ja)
    :Fehlerhafte Werte;
    stop
else (nein)
endif
    
:Fehlmenge / Wirkungsgrad;
    
:Benötigte Energie;

:Leistung / Wirkungsgrad;
    
:Maximal abzugebende Energie;
    
if (Leistung >= Fehlmenge ?) then (ja)
    if (Verfügbare Energie >= Benötigte Energie ?) then (ja)
        :Bedarf wird komplett gedeckt
        Speicher um Benötigte Energie entladen;
        stop
    else (nein) 
        :Verfügbare Energie wird komplett abgegeben;
        stop
        
    endif

(nein) elseif (Verfügbare Energie >= Leistung ?) then (ja)
    :Verfügbare Energie durch Leistung begrenzt
    Maximal abzugebende Energie wird entladen;
        stop
else (nein)
    :Verfügbare Energie durch Speicher begrenzt
    Speicher wird komplett entladen;
    stop

endif

@enduml