@startuml Fallunterscheidung

<style>
activity {
    HorizontalAlignment center
}

</style>
!pragma useVerticalIf on
start
    
if (Lademenge <= 0 ?) then (ja)
    :Fehlerhafte Lademenge;
    stop
else (nein)
endif
    
:Lademenge <latex>\cdot</latex> Wirkungsgrad;
    
:Maximal lieferbare Energie;
    
if (    Ladestand > (Obere Ladegrenze - Leistung) ?
Speicher fast voll, Leistung ausreichend um zu füllen) then (ja)
    if (Maximal lieferbare Energie >= Speicherplatz ?) then (ja)
        :Speicher wird voll geladen
        Ladungs-Energie durch Platz begrenzt;
        stop
    else (nein) 
        :Lademenge wird komplett eingespiesen;
        stop
        
    endif

(nein) elseif (Leistung > Maximal lieferbare Energie ?) then (ja)
    :Lademenge wird komplett eingespiesen;
        stop
else (nein)
    :Lademenge wird nur zum Teil eingespiesen
    Ladungs-Energie durch Leistung begrenzt;
    stop

endif

@enduml