@startuml Verbrauchsprognose
skinparam ActivityFontSize 30
start

:Input Daten
- SMARD-Verbrauch 2024 (V_2024)
- Zielwerte 2030 (Zi_2030)
- Zielwerte 2045 (Zi_2045);

:Berechne jährliche Zuwächse
r_2030 = ((Zi_2030 / V_2024_gesamt) ^ (1/6)) - 1 
r_2045 = ((Zi_2045 / Zi_2030) ^ (1/15)) - 1;

:Erstellung des Basisprofils bis 2030
- V_2024 Gruppierung nach Monat/Tag der Woche/Uhrzeit
- Durchschnittsbildung;

:Berechnung Verbrauchsprognose bis 2030
- Dataframe mit Datum von 1.1.2026 00:00 bis 31.12.2030 23:45 erstellen
V_2030 = V_2024_Basis * (1 + r_2030) ^ (Jahr - 2024);

:Erstellung des Basisprofils bis 2045
- V_2030 Gruppierung nach Monat/Tag der Woche/Uhrzeit
- Durchschnittsbildung;

:Berechnung Verbrauchsprognose bis 2045
- Dataframe mit Datum von 1.1.2031 00:00 bis 31.12.2045 23:45 erstellen
V_2045 = V_2030_Basis * (1 + r_2045) ^ (Jahr - 2030);

:Zusammenführung der Prognosedaten
- V_gesamt = V_2030 + V_2045;

:Export Prognosedaten
(2026–2045);


@enduml
